export interface Product {
  id: string;
  name: string;
  code: string;
  category: string;
  tagline: string;
  description: string;
  quantity: string;
  form: string;
  purity: string;
  storage: string;
  handling: string;
  priceFrom: number;
  prices: { qty: string; price: number }[];
  inStock: boolean;
  featured: boolean;
  labFavorite?: boolean;
  badge?: string;
  slug: string;
  image?: string;
}

export const products: Product[] = [
  {
    id: "bpc-157",
    slug: "bpc-157",
    image: "/images/bpc-157.png",
    name: "BPC-157",
    code: "BPC-157",
    category: "Peptides",
    tagline: "Body Protection Compound for advanced laboratory research applications.",
    description:
      "BPC-157 is a synthetic pentadecapeptide research chemical composed of 15 amino acids, supplied by Gills Bio Lab strictly for laboratory applications. This compound is not approved for human or veterinary use and must not be used for diagnosis, treatment, or any form of therapeutic or cosmetic application. Produced with a focus on consistency and reliability, BPC-157 is suitable for in vitro, analytical, and other controlled research settings where peptide behavior, stability, and interaction are under investigation.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 50,
    prices: [{ qty: "10 mg × 1", price: 50 }],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "selank",
    slug: "selank",
    image: "/images/selank.png",
    name: "Selank",
    code: "SEL",
    category: "Neuropeptides",
    tagline: "Anxiolytic heptapeptide research chemical for neuropeptide studies.",
    description:
      "Selank is a synthetic heptapeptide research chemical derived from tuftsin, supplied by Gills Bio Lab for laboratory use only. Suitable for in vitro and controlled neuropeptide research investigating GABAergic modulation and peptide–receptor interaction.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 50,
    prices: [{ qty: "10 mg × 1", price: 50 }],
    inStock: true,
    featured: true,
  },
  {
    id: "ghk-cu",
    slug: "ghk-cu",
    image: "/images/ghk-cu.png",
    name: "GHK-Cu",
    code: "GHK-Cu",
    category: "Peptides",
    tagline: "Copper-binding tripeptide research chemical for collagen synthesis pathway studies.",
    description:
      "GHK-Cu is a naturally occurring copper-binding tripeptide supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into copper peptide biology, collagen synthesis signaling pathways, and related controlled laboratory investigations.",
    quantity: "50 mg – 100 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 30,
    prices: [
      { qty: "50 mg × 1", price: 30 },
      { qty: "100 mg × 1", price: 50 },
    ],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "kpv",
    slug: "kpv",
    image: "/images/kpv.png",
    name: "KPV",
    code: "KPV",
    category: "Peptides",
    tagline: "Alpha-MSH-derived tripeptide research chemical for inflammation studies.",
    description:
      "KPV is a C-terminal tripeptide fragment of alpha-melanocyte-stimulating hormone supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into melanocortin signaling, inflammatory pathway modulation, and peptide–receptor interactions.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 45,
    prices: [{ qty: "10 mg × 1", price: 45 }],
    inStock: true,
    featured: true,
  },
  {
    id: "ss-31",
    slug: "ss-31",
    image: "/images/ss-31.png",
    name: "SS-31",
    code: "SS-31",
    category: "Mitochondrial Research",
    tagline: "Mitochondria-targeted tetrapeptide research chemical for membrane dynamics studies.",
    description:
      "SS-31 (Szeto-Schiller peptide 31) is a mitochondria-targeted tetrapeptide research chemical supplied by Gills Bio Lab for laboratory use only. Suitable for in vitro research into mitochondrial membrane dynamics, reactive oxygen species (ROS) pathway investigations, and cardiolipin-targeted peptide interactions.",
    quantity: "50 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 206,
    prices: [{ qty: "50 mg × 1", price: 206 }],
    inStock: true,
    featured: true,
    badge: "New",
  },
  {
    id: "mots-c",
    slug: "mots-c",
    image: "/images/mots-c.png",
    name: "MOTS-C",
    code: "MOTS",
    category: "Mitochondrial Research",
    tagline: "Mitochondrial-derived peptide research chemical for metabolic studies.",
    description:
      "MOTS-C is a mitochondrial open reading frame peptide supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into mitochondrial signaling, AMPK pathway activation, and metabolic regulation at the cellular level.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 179,
    prices: [{ qty: "10 mg × 1", price: 179 }],
    inStock: true,
    featured: true,
    badge: "New",
  },
  {
    id: "nad-plus",
    slug: "nad-plus",
    image: "/images/nad-plus.png",
    name: "NAD+",
    code: "NAD+",
    category: "Metabolic / NAD",
    tagline: "Nicotinamide adenine dinucleotide research chemical for cellular energy studies.",
    description:
      "NAD+ (Nicotinamide Adenine Dinucleotide) is a vital coenzyme supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into cellular energy metabolism, sirtuin activation, DNA repair pathways, and mitochondrial bioenergetics.",
    quantity: "500 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "Store at 2-8°C (36-46°F)",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 60,
    prices: [{ qty: "500 mg × 1", price: 60 }],
    inStock: true,
    featured: true,
    labFavorite: true,
    badge: "New",
  },
  {
    id: "glow-blend",
    slug: "glow-blend",
    image: "/images/glow-blend.png",
    name: "\"Glow\" Blend",
    code: "GLOW",
    category: "Blends",
    tagline: "BPC-157 10 mg + GHK-Cu 50 mg + TB-500 10 mg precision research blend.",
    description:
      "The Gills Bio Lab \"Glow\" Blend combines BPC-157 (10 mg), GHK-Cu (50 mg), and TB-500 (10 mg) in a single precision-blended vial. Supplied as a research chemical for laboratory use only. Suitable for in vitro studies examining the combined interaction profiles of these peptide and copper-tripeptide compounds in a controlled laboratory setting.",
    quantity: "70 mg total / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 90,
    prices: [{ qty: "70 mg × 1", price: 90 }],
    inStock: true,
    featured: true,
    labFavorite: true,
    badge: "New",
  },
  {
    id: "cjc-ipa-blend-5",
    slug: "cjc-ipa-blend-5",
    image: "/images/cjc-ipa.png",
    name: "CJC-1295 / Ipamorelin",
    code: "CJC+IPA",
    category: "Blends",
    tagline: "CJC-1295 No DAC 10 mg + Ipamorelin 10 mg synergistic research blend.",
    description:
      "A precision blend of CJC-1295 No DAC (10 mg) and Ipamorelin (10 mg) supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro studies examining combined GHRH analogue and GH secretagogue receptor interactions in a single formulation.",
    quantity: "20 mg / vial (10 mg + 10 mg)",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 110,
    prices: [{ qty: "20 mg × 1", price: 110 }],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "semax",
    slug: "semax",
    image: "/images/semax.png",
    name: "Semax",
    code: "SEMAX",
    category: "Neuropeptides",
    tagline: "ACTH-derived heptapeptide research chemical for cognitive and neuroprotective pathway studies.",
    description:
      "Semax is a synthetic heptapeptide analogue of ACTH(4–10) supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into BDNF-related signaling, dopaminergic and serotonergic pathway modulation, and neuropeptide–receptor interactions in controlled research settings.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "Store at 2-8°C (36-46°F)",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 45,
    prices: [{ qty: "10 mg × 1", price: 45 }],
    inStock: true,
    featured: true,
    badge: "New",
  },
  {
    id: "bacteriostatic-water",
    slug: "bacteriostatic-water",
    image: "/images/bacteriostatic-water.png",
    name: "Bacteriostatic Water",
    code: "BAC-H2O",
    category: "Ancillaries",
    tagline: "0.9% benzyl alcohol sterile solution for peptide reconstitution in laboratory settings.",
    description:
      "Bacteriostatic Water (0.9% benzyl alcohol in sterile water) is supplied by Gills Bio Lab as a laboratory ancillary for research use only. Suitable for the reconstitution of lyophilized peptide research chemicals in controlled in vitro settings. Not for injection or human use.",
    quantity: "10 mL / vial",
    form: "Sterile solution",
    purity: "USP-grade",
    storage: "Store at 2-25°C (36-77°F)",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 18,
    prices: [{ qty: "10 mL × 1", price: 18 }],
    inStock: true,
    featured: false,
  },
  {
    id: "retatrutide",
    slug: "retatrutide",
    image: "/images/retatrutide.png",
    name: "Retatrutide",
    code: "RET",
    category: "GLP-1 / Metabolic",
    tagline: "Triple GIP/GLP-1/glucagon receptor agonist research chemical.",
    description:
      "Retatrutide is a synthetic triple agonist targeting GIP, GLP-1, and glucagon receptors, supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into multi-receptor incretin pharmacology and energy homeostasis pathways.",
    quantity: "10 mg – 30 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 90,
    prices: [
      { qty: "10 mg × 1", price: 90 },
      { qty: "20 mg × 1", price: 150 },
      { qty: "30 mg × 1", price: 180 },
    ],
    inStock: true,
    featured: true,
    badge: "New",
  },
  {
    id: "tesamorelin",
    slug: "tesamorelin",
    image: "/images/tb-500.png",
    name: "Tesamorelin",
    code: "TESA",
    category: "Peptides",
    tagline: "Synthetic GHRH analogue research chemical for growth hormone pathway studies.",
    description:
      "Tesamorelin is a synthetic analogue of growth hormone-releasing hormone (GHRH) supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into GH secretagogue receptor signaling, pituitary axis pathway modulation, and related controlled laboratory investigations.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 60,
    prices: [{ qty: "10 mg × 1", price: 60 }],
    inStock: true,
    featured: true,
    badge: "New",
  },
  {
    id: "mt2",
    slug: "mt2",
    image: "/images/mt2.png",
    name: "Melanotan II",
    code: "MT-2",
    category: "Peptides",
    tagline: "Cyclic lactam analogue of alpha-MSH research chemical for melanocortin studies.",
    description:
      "Melanotan II (MT-2) is a synthetic cyclic lactam analogue of alpha-melanocyte-stimulating hormone supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into melanocortin receptor binding, pigmentation pathway signaling, and related controlled laboratory investigations.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 29.99,
    prices: [{ qty: "10 mg × 1", price: 29.99 }],
    inStock: true,
    featured: true,
    badge: "New",
  },
];

export const categories = [
  "All",
  "Peptides",
  "Neuropeptides",
  "Mitochondrial Research",
  "Metabolic / NAD",
  "GLP-1 / Metabolic",
  "Blends",
  "Ancillaries",
];

export const featuredProducts = products.filter((p) => p.featured);

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
