export interface Product {
  id: string;
  name: string;
  code: string;
  category: string;
  tagline: string;
  description: string;
  quantity: string;
  form: string;
  purity: string;
  storage: string;
  handling: string;
  priceFrom: number;
  prices: { qty: string; price: number }[];
  inStock: boolean;
  featured: boolean;
  labFavorite?: boolean;
  badge?: string;
  slug: string;
}

export const products: Product[] = [
  // ── Existing products ──────────────────────────────────────────────────────
  {
    id: "bpc-157",
    slug: "bpc-157",
    name: "BPC-157",
    code: "BPC-157",
    category: "Peptides",
    tagline: "Body Protection Compound for advanced laboratory research applications.",
    description:
      "BPC-157 is a synthetic pentadecapeptide research chemical composed of 15 amino acids, supplied by Gills Bio Lab strictly for laboratory applications. This compound is not approved for human or veterinary use and must not be used for diagnosis, treatment, or any form of therapeutic or cosmetic application. Produced with a focus on consistency and reliability, BPC-157 is suitable for in vitro, analytical, and other controlled research settings where peptide behavior, stability, and interaction are under investigation.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 64,
    prices: [{ qty: "10 mg × 1", price: 64 }],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "tb-500",
    slug: "tb-500",
    name: "TB-500",
    code: "TB-500",
    category: "Peptides",
    tagline: "Thymosin Beta-4 fragment for in vitro peptide research studies.",
    description:
      "TB-500 is a synthetic analogue of the naturally occurring peptide Thymosin Beta-4. Supplied by Gills Bio Lab as a research chemical for laboratory use only. This compound is intended strictly for in vitro and analytical applications. Each unit is prepared and packaged to support demanding research workflows and storage conditions.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 72,
    prices: [{ qty: "10 mg × 1", price: 72 }],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "ghrp-6",
    slug: "ghrp-6",
    name: "GHRP-6",
    code: "GHRP-6",
    category: "Growth Factors",
    tagline: "Growth Hormone Releasing Peptide-6 research chemical for laboratory study.",
    description:
      "GHRP-6 is a synthetic hexapeptide research chemical supplied by Gills Bio Lab for laboratory applications only. It is not approved for human or veterinary use. Suitable for controlled research into growth hormone releasing peptides, receptor binding studies, and related in vitro investigations.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 24.99,
    prices: [
      { qty: "5 mg × 1", price: 24.99 },
      { qty: "5 mg × 5", price: 109.99 },
      { qty: "5 mg × 10", price: 199.99 },
    ],
    inStock: true,
    featured: false,
  },
  {
    id: "ghrp-2",
    slug: "ghrp-2",
    name: "GHRP-2",
    code: "GHRP-2",
    category: "Growth Factors",
    tagline: "Growth Hormone Releasing Peptide-2 for advanced in vitro research.",
    description:
      "GHRP-2 is a synthetic hexapeptide research chemical supplied by Gills Bio Lab for laboratory use only. This compound is suitable for in vitro and controlled research settings investigating growth hormone secretagogue activity and peptide interaction profiles.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 22.99,
    prices: [
      { qty: "5 mg × 1", price: 22.99 },
      { qty: "5 mg × 5", price: 99.99 },
      { qty: "5 mg × 10", price: 184.99 },
    ],
    inStock: true,
    featured: false,
  },
  {
    id: "ipamorelin",
    slug: "ipamorelin",
    name: "Ipamorelin",
    code: "IPM",
    category: "Growth Factors",
    tagline: "Selective growth hormone secretagogue for controlled research settings.",
    description:
      "Ipamorelin is a synthetic pentapeptide research chemical supplied by Gills Bio Lab for laboratory applications only. It is suitable for in vitro and analytical research investigating selective GH secretagogue receptor activity and peptide selectivity profiles.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 49,
    prices: [{ qty: "5 mg × 1", price: 49 }],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "mgf",
    slug: "mgf",
    name: "MGF",
    code: "MGF",
    category: "Growth Factors",
    tagline: "Mechano Growth Factor peptide research chemical for laboratory study.",
    description:
      "MGF (Mechano Growth Factor) is an isoform of IGF-1 supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into growth factor peptides, receptor binding behavior, and related molecular investigations.",
    quantity: "2 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 32.99,
    prices: [
      { qty: "2 mg × 1", price: 32.99 },
      { qty: "2 mg × 5", price: 139.99 },
      { qty: "2 mg × 10", price: 254.99 },
    ],
    inStock: true,
    featured: false,
  },
  {
    id: "pt-141",
    slug: "pt-141",
    name: "PT-141",
    code: "PT-141",
    category: "Neuropeptides",
    tagline: "Melanocortin receptor agonist peptide for advanced laboratory research.",
    description:
      "PT-141 (Bremelanotide) is a synthetic cyclic heptapeptide research chemical supplied by Gills Bio Lab for laboratory use only. It is intended strictly for in vitro and controlled research investigating melanocortin receptor pharmacology and peptide behavior.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 44.99,
    prices: [
      { qty: "10 mg × 1", price: 44.99 },
      { qty: "10 mg × 5", price: 199.99 },
      { qty: "10 mg × 10", price: 374.99 },
    ],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "melanotan-2",
    slug: "melanotan-2",
    name: "MT-2 (Melanotan 2 Acetate)",
    code: "MT-2",
    category: "Neuropeptides",
    tagline: "Melanocyte-stimulating hormone analogue research chemical.",
    description:
      "Melanotan II Acetate is a synthetic analogue of alpha-melanocyte-stimulating hormone supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro and controlled research into melanocortin receptor binding and peptide structural studies.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 39,
    prices: [{ qty: "10 mg × 1", price: 39 }],
    inStock: true,
    featured: false,
  },
  {
    id: "selank",
    slug: "selank",
    name: "Selank",
    code: "SEL",
    category: "Neuropeptides",
    tagline: "Anxiolytic heptapeptide research chemical for neuropeptide studies.",
    description:
      "Selank is a synthetic heptapeptide research chemical derived from tuftsin, supplied by Gills Bio Lab for laboratory use only. Suitable for in vitro and controlled neuropeptide research investigating GABAergic modulation and peptide–receptor interaction.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 47,
    prices: [{ qty: "10 mg × 1", price: 47 }],
    inStock: true,
    featured: false,
  },
  {
    id: "semax",
    slug: "semax",
    name: "Semax",
    code: "SMX",
    category: "Neuropeptides",
    tagline: "ACTH-derived neuropeptide research chemical for laboratory study.",
    description:
      "Semax is a synthetic heptapeptide research chemical derived from the ACTH sequence, supplied by Gills Bio Lab for laboratory use only. It is suitable for in vitro and controlled research into neuropeptide pharmacology and related peptide behavior studies.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 47,
    prices: [{ qty: "10 mg × 1", price: 47 }],
    inStock: true,
    featured: true,
  },
  {
    id: "epithalon",
    slug: "epithalon",
    name: "Epithalon",
    code: "EPT",
    category: "Peptides",
    tagline: "Telomeric tetrapeptide research chemical for laboratory applications.",
    description:
      "Epithalon is a synthetic tetrapeptide research chemical supplied by Gills Bio Lab for laboratory use only. Suitable for in vitro and analytical research investigating telomere-related peptide behavior, bioregulator studies, and related controlled applications.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 29.99,
    prices: [
      { qty: "10 mg × 1", price: 29.99 },
      { qty: "10 mg × 5", price: 129.99 },
      { qty: "10 mg × 10", price: 239.99 },
    ],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "dsip",
    slug: "dsip",
    name: "DSIP",
    code: "DSIP",
    category: "Neuropeptides",
    tagline: "Delta sleep-inducing peptide research chemical for laboratory use.",
    description:
      "DSIP (Delta Sleep-Inducing Peptide) is a nonapeptide research chemical supplied by Gills Bio Lab for laboratory use only. Suitable for in vitro and controlled neuropeptide research exploring peptide receptor pharmacology and sleep-related peptide behavior.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 97%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 44,
    prices: [{ qty: "5 mg × 1", price: 44 }],
    inStock: true,
    featured: false,
  },
  {
    id: "hexarelin",
    slug: "hexarelin",
    name: "Hexarelin",
    code: "HEX",
    category: "Growth Factors",
    tagline: "Hexapeptide growth hormone secretagogue for in vitro research.",
    description:
      "Hexarelin is a synthetic hexapeptide research chemical supplied by Gills Bio Lab for laboratory use only. It is a potent GH secretagogue suitable for in vitro research into receptor binding kinetics and growth factor peptide behavior.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 28.99,
    prices: [
      { qty: "5 mg × 1", price: 28.99 },
      { qty: "5 mg × 5", price: 124.99 },
      { qty: "5 mg × 10", price: 229.99 },
    ],
    inStock: false,
    featured: false,
    badge: "Backorder",
  },
  {
    id: "mod-grf",
    slug: "mod-grf",
    name: "Mod GRF (1-29)",
    code: "MOD-GRF",
    category: "Growth Factors",
    tagline: "Modified GHRH fragment research chemical for laboratory peptide studies.",
    description:
      "Mod GRF 1-29 is a shortened form of growth hormone releasing hormone supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research investigating truncated GHRH receptor interactions and related peptide stability studies.",
    quantity: "2 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 26.99,
    prices: [
      { qty: "2 mg × 1", price: 26.99 },
      { qty: "2 mg × 5", price: 114.99 },
      { qty: "2 mg × 10", price: 209.99 },
    ],
    inStock: true,
    featured: false,
  },
  {
    id: "kisspeptin-10",
    slug: "kisspeptin-10",
    name: "Kisspeptin-10",
    code: "KP-10",
    category: "Neuropeptides",
    tagline: "Hypothalamic neuropeptide research chemical for specialized laboratory applications.",
    description:
      "Kisspeptin-10 is a synthetic decapeptide research chemical supplied by Gills Bio Lab for laboratory use only. Suitable for in vitro and controlled research into GPR54 receptor pharmacology, reproductive neuroendocrinology, and related peptide investigations.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 45.99,
    prices: [
      { qty: "5 mg × 1", price: 45.99 },
      { qty: "5 mg × 5", price: 204.99 },
      { qty: "5 mg × 10", price: 379.99 },
    ],
    inStock: true,
    featured: false,
  },

  // ── NEW products ───────────────────────────────────────────────────────────
  {
    id: "semaglutide",
    slug: "semaglutide",
    name: "Semaglutide",
    code: "SEM",
    category: "GLP-1 / Metabolic",
    tagline: "GLP-1 receptor agonist research chemical for metabolic pathway studies.",
    description:
      "Semaglutide is a synthetic GLP-1 receptor agonist supplied by Gills Bio Lab as a research chemical for laboratory use only. It is not approved for human or veterinary use. Suitable for in vitro and controlled research into incretin signaling, metabolic pathway modulation, and related peptide receptor pharmacology.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 139,
    prices: [{ qty: "10 mg × 1", price: 139 }],
    inStock: true,
    featured: true,
    labFavorite: true,
    badge: "New",
  },
  {
    id: "tirzepatide",
    slug: "tirzepatide",
    name: "Tirzepatide",
    code: "TIR",
    category: "GLP-1 / Metabolic",
    tagline: "Dual GIP/GLP-1 receptor agonist research chemical for metabolic studies.",
    description:
      "Tirzepatide is a synthetic dual glucose-dependent insulinotropic polypeptide (GIP) and GLP-1 receptor agonist supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into dual incretin receptor pharmacology and metabolic signaling pathways.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 169,
    prices: [{ qty: "5 mg × 1", price: 169 }],
    inStock: true,
    featured: true,
    labFavorite: true,
    badge: "New",
  },
  {
    id: "retatrutide-10",
    slug: "retatrutide-10",
    name: "Retatrutide 10 mg",
    code: "RET-10",
    category: "GLP-1 / Metabolic",
    tagline: "Triple GIP/GLP-1/glucagon receptor agonist research chemical.",
    description:
      "Retatrutide is a synthetic triple agonist targeting GIP, GLP-1, and glucagon receptors, supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into multi-receptor incretin pharmacology and energy homeostasis pathways.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 179,
    prices: [{ qty: "10 mg × 1", price: 179 }],
    inStock: true,
    featured: true,
    badge: "New",
  },
  {
    id: "retatrutide-20",
    slug: "retatrutide-20",
    name: "Retatrutide 20 mg",
    code: "RET-20",
    category: "GLP-1 / Metabolic",
    tagline: "Triple GIP/GLP-1/glucagon receptor agonist – high-load vial.",
    description:
      "Retatrutide 20 mg is a high-concentration vial of the triple agonist peptide supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for extended in vitro studies requiring larger sample volumes of this multi-receptor incretin research compound.",
    quantity: "20 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 219,
    prices: [{ qty: "20 mg × 1", price: 219 }],
    inStock: true,
    featured: false,
    badge: "New",
  },
  {
    id: "bpc-tb-blend",
    slug: "bpc-tb-blend",
    name: "BPC-157 / TB-500 Blend",
    code: "BPC+TB",
    category: "Blends",
    tagline: "Combined BPC-157 5 mg + TB-500 5 mg blend for comprehensive research.",
    description:
      "A precision-blended vial containing 5 mg BPC-157 and 5 mg TB-500, supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro studies examining the combined behavior of these two widely researched peptides in a single controlled formulation.",
    quantity: "10 mg total / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 99,
    prices: [{ qty: "10 mg × 1", price: 99 }],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "hcg",
    slug: "hcg",
    name: "HCG",
    code: "HCG",
    category: "Hormonal Research",
    tagline: "Human chorionic gonadotropin research chemical for endocrine studies.",
    description:
      "HCG (Human Chorionic Gonadotropin) equivalent supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro and controlled research into gonadotropin receptor pharmacology and reproductive endocrinology pathways.",
    quantity: "5,000 IU equiv. / vial",
    form: "Lyophilized powder",
    purity: "≥ 97%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 54,
    prices: [{ qty: "5,000 IU × 1", price: 54 }],
    inStock: true,
    featured: false,
  },
  {
    id: "ss-31",
    slug: "ss-31",
    name: "SS-31",
    code: "SS-31",
    category: "Mitochondrial Research",
    tagline: "Mitochondria-targeted antioxidant peptide research chemical.",
    description:
      "SS-31 (Szeto-Schiller peptide 31) is a mitochondria-targeted tetrapeptide research chemical supplied by Gills Bio Lab for laboratory use only. Suitable for in vitro research into mitochondrial membrane dynamics, oxidative stress pathways, and cardiolipin-targeted peptide interactions.",
    quantity: "50 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 149,
    prices: [{ qty: "50 mg × 1", price: 149 }],
    inStock: true,
    featured: true,
    badge: "New",
  },
  {
    id: "cjc-1295-no-dac",
    slug: "cjc-1295-no-dac",
    name: "CJC-1295 No DAC",
    code: "CJC-ND",
    category: "Growth Factors",
    tagline: "Short-acting GHRH analogue without DAC for pulsatile research protocols.",
    description:
      "CJC-1295 without DAC (Drug Affinity Complex) is a synthetic GHRH analogue supplied by Gills Bio Lab as a research chemical for laboratory use only. Its shorter half-life compared to the DAC form makes it suitable for in vitro research modeling pulsatile GH secretion and receptor interaction kinetics.",
    quantity: "2 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 44,
    prices: [{ qty: "2 mg × 1", price: 44 }],
    inStock: true,
    featured: false,
  },
  {
    id: "cjc-ipa-blend-5",
    slug: "cjc-ipa-blend-5",
    name: "CJC-1295 No DAC + Ipamorelin 5+5",
    code: "CJC+IPA-5",
    category: "Blends",
    tagline: "CJC-1295 No DAC 5 mg + Ipamorelin 5 mg synergistic research blend.",
    description:
      "A precision blend of CJC-1295 No DAC (5 mg) and Ipamorelin (5 mg) supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro studies examining combined GHRH analogue and GH secretagogue receptor interactions in a single formulation.",
    quantity: "10 mg total / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 89,
    prices: [{ qty: "10 mg × 1", price: 89 }],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "cjc-ipa-blend-10",
    slug: "cjc-ipa-blend-10",
    name: "CJC-1295 No DAC + Ipamorelin 10+10",
    code: "CJC+IPA-10",
    category: "Blends",
    tagline: "CJC-1295 No DAC 10 mg + Ipamorelin 10 mg high-load research blend.",
    description:
      "A high-load precision blend of CJC-1295 No DAC (10 mg) and Ipamorelin (10 mg) supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for extended in vitro studies requiring larger volumes of this dual-peptide GHRH/secretagogue research formulation.",
    quantity: "20 mg total / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 159,
    prices: [{ qty: "20 mg × 1", price: 159 }],
    inStock: true,
    featured: false,
  },
  {
    id: "cjc-1295-dac",
    slug: "cjc-1295-dac",
    name: "CJC-1295 DAC",
    code: "CJC-DAC",
    category: "Growth Factors",
    tagline: "Long-acting GHRH analogue with Drug Affinity Complex for sustained research.",
    description:
      "CJC-1295 with DAC is a synthetic GHRH analogue incorporating the Drug Affinity Complex for extended half-life. Supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research investigating sustained GHRH receptor activation and long-acting peptide kinetics.",
    quantity: "2 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 54,
    prices: [{ qty: "2 mg × 1", price: 54 }],
    inStock: true,
    featured: false,
  },
  {
    id: "sermorelin",
    slug: "sermorelin",
    name: "Sermorelin",
    code: "SRM",
    category: "Growth Factors",
    tagline: "GHRH 1-29 analogue research chemical for growth factor laboratory studies.",
    description:
      "Sermorelin is a synthetic analogue of the first 29 amino acids of endogenous GHRH, supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro investigations into GHRH receptor binding affinity and growth hormone secretagogue receptor pharmacology.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 54,
    prices: [{ qty: "5 mg × 1", price: 54 }],
    inStock: true,
    featured: false,
  },
  {
    id: "follistatin",
    slug: "follistatin",
    name: "Follistatin",
    code: "FST",
    category: "Growth Factors",
    tagline: "Activin-binding glycoprotein research chemical for myostatin pathway studies.",
    description:
      "Follistatin is a glycoprotein research chemical supplied by Gills Bio Lab for laboratory use only. It acts as a binding protein for activin and myostatin. Suitable for in vitro research into TGF-β superfamily signaling, myostatin pathway regulation, and related controlled investigations.",
    quantity: "1 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 119,
    prices: [{ qty: "1 mg × 1", price: 119 }],
    inStock: true,
    featured: true,
    badge: "New",
  },
  {
    id: "igf-1-lr3",
    slug: "igf-1-lr3",
    name: "IGF-1 LR3",
    code: "IGF-LR3",
    category: "Growth Factors",
    tagline: "Long R3 insulin-like growth factor research chemical for laboratory use.",
    description:
      "IGF-1 LR3 is a synthetic long-acting variant of insulin-like growth factor 1, supplied by Gills Bio Lab as a research chemical for laboratory use only. Its extended half-life compared to native IGF-1 makes it suitable for in vitro research into IGF receptor signaling and anabolic pathway studies.",
    quantity: "1 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 94,
    prices: [{ qty: "1 mg × 1", price: 94 }],
    inStock: true,
    featured: true,
  },
  {
    id: "tesamorelin",
    slug: "tesamorelin",
    name: "Tesamorelin",
    code: "TES",
    category: "Growth Factors",
    tagline: "GHRH analogue research chemical for GH axis in vitro studies.",
    description:
      "Tesamorelin is a synthetic trans-3-hexenoic acid-conjugated GHRH analogue supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research investigating GHRH receptor binding, GH axis peptide pharmacology, and related controlled studies.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 114,
    prices: [{ qty: "10 mg × 1", price: 114 }],
    inStock: true,
    featured: false,
  },
  {
    id: "ghk-cu-10",
    slug: "ghk-cu-10",
    name: "GHK-Cu 10 mg",
    code: "GHK-10",
    category: "Peptides",
    tagline: "Copper-binding tripeptide research chemical for dermal and regenerative studies.",
    description:
      "GHK-Cu is a naturally occurring copper-binding tripeptide supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into copper peptide biology, collagen synthesis pathways, and related controlled dermal and regenerative investigations.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 32,
    prices: [{ qty: "10 mg × 1", price: 32 }],
    inStock: true,
    featured: false,
    labFavorite: true,
  },
  {
    id: "ghk-cu-100",
    slug: "ghk-cu-100",
    name: "GHK-Cu 100 mg",
    code: "GHK-100",
    category: "Peptides",
    tagline: "High-volume copper tripeptide vial for large-scale laboratory research.",
    description:
      "GHK-Cu 100 mg is a bulk-quantity copper-binding tripeptide supplied by Gills Bio Lab as a research chemical for laboratory use only. Ideal for large-scale in vitro studies requiring significant quantities of this copper peptide research compound.",
    quantity: "100 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 169,
    prices: [{ qty: "100 mg × 1", price: 169 }],
    inStock: true,
    featured: false,
  },
  {
    id: "mots-c",
    slug: "mots-c",
    name: "MOTS-C",
    code: "MOTS",
    category: "Mitochondrial Research",
    tagline: "Mitochondrial-derived peptide research chemical for metabolic studies.",
    description:
      "MOTS-C is a mitochondrial open reading frame peptide supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into mitochondrial signaling, AMPK pathway activation, and metabolic regulation at the cellular level.",
    quantity: "40 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 179,
    prices: [{ qty: "40 mg × 1", price: 179 }],
    inStock: true,
    featured: true,
    badge: "New",
  },
  {
    id: "foxo4",
    slug: "foxo4",
    name: "FOXO4-DRI",
    code: "FOXO4",
    category: "Peptides",
    tagline: "D-retro-inverso FOXO4 peptide research chemical for senolytic studies.",
    description:
      "FOXO4-DRI is a D-retro-inverso peptide research chemical supplied by Gills Bio Lab for laboratory use only. Suitable for in vitro research into senescent cell biology, apoptosis signaling pathways, and FOXO4-p53 protein–protein interactions under controlled laboratory conditions.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 259,
    prices: [{ qty: "10 mg × 1", price: 259 }],
    inStock: true,
    featured: true,
    labFavorite: true,
    badge: "New",
  },
  {
    id: "melatonin-injectable",
    slug: "melatonin-injectable",
    name: "Melatonin (Research Injectable)",
    code: "MEL",
    category: "Neuropeptides",
    tagline: "Research-grade melatonin for circadian and antioxidant pathway studies.",
    description:
      "Melatonin research injectable is supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro and controlled research into circadian rhythm signaling, MT1/MT2 receptor pharmacology, and antioxidant pathway investigations.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 24,
    prices: [{ qty: "10 mg × 1", price: 24 }],
    inStock: true,
    featured: false,
  },
  {
    id: "nad-plus",
    slug: "nad-plus",
    name: "NAD+",
    code: "NAD+",
    category: "Metabolic / NAD",
    tagline: "Nicotinamide adenine dinucleotide research chemical for cellular energy studies.",
    description:
      "NAD+ (Nicotinamide Adenine Dinucleotide) is a vital coenzyme supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into cellular energy metabolism, sirtuin activation, DNA repair pathways, and mitochondrial bioenergetics.",
    quantity: "250 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 79,
    prices: [{ qty: "250 mg × 1", price: 79 }],
    inStock: true,
    featured: true,
    labFavorite: true,
    badge: "New",
  },
  {
    id: "kpv",
    slug: "kpv",
    name: "KPV",
    code: "KPV",
    category: "Peptides",
    tagline: "Alpha-MSH-derived tripeptide research chemical for inflammation studies.",
    description:
      "KPV is a C-terminal tripeptide fragment of alpha-melanocyte-stimulating hormone supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into melanocortin signaling, inflammatory pathway modulation, and peptide–receptor interactions.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 47,
    prices: [{ qty: "10 mg × 1", price: 47 }],
    inStock: true,
    featured: false,
  },
  {
    id: "glow-blend",
    slug: "glow-blend",
    name: "\"Glow\" Blend",
    code: "GLOW",
    category: "Blends",
    tagline: "BPC-157 10 mg + GHK-Cu 50 mg + TB-500 10 mg premium regenerative blend.",
    description:
      "The Gills Bio Lab \"Glow\" Blend combines BPC-157 (10 mg), GHK-Cu (50 mg), and TB-500 (10 mg) in a single precision-blended vial. Supplied as a research chemical for laboratory use only. Suitable for in vitro studies examining the combined peptide and copper-tripeptide interactions in a dermal and regenerative research context.",
    quantity: "70 mg total / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 169,
    prices: [{ qty: "70 mg × 1", price: 169 }],
    inStock: true,
    featured: true,
    labFavorite: true,
    badge: "New",
  },
  {
    id: "hgh-frag-176-191",
    slug: "hgh-frag-176-191",
    name: "HGH Fragment 176–191",
    code: "HGH-FRAG",
    category: "Growth Factors",
    tagline: "C-terminal HGH fragment research chemical for lipolytic pathway studies.",
    description:
      "HGH Fragment 176-191 is a synthetic peptide fragment corresponding to amino acids 176–191 of human growth hormone, supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into lipolytic signaling, adipocyte biology, and HGH receptor fragment interaction studies.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 57,
    prices: [{ qty: "5 mg × 1", price: 57 }],
    inStock: true,
    featured: false,
  },
  {
    id: "benzyl-alcohol",
    slug: "benzyl-alcohol",
    name: "Benzyl Alcohol 0.9%",
    code: "BA-0.9",
    category: "Reconstitution Supplies",
    tagline: "Bacteriostatic preservative solution for peptide reconstitution in research settings.",
    description:
      "Benzyl Alcohol 0.9% is a bacteriostatic preservative solution supplied by Gills Bio Lab for laboratory and research use only. Suitable for use as a reconstitution vehicle for lyophilized peptide research chemicals in controlled laboratory settings.",
    quantity: "10 ml / vial",
    form: "Sterile solution",
    purity: "≥ 99.5%",
    storage: "Room temperature, protected from light",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 12,
    prices: [{ qty: "10 ml × 1", price: 12 }],
    inStock: true,
    featured: false,
  },
  {
    id: "cu50-tb10-bc10-kpv10",
    slug: "cu50-tb10-bc10-kpv10",
    name: "Multi-Blend (CU50+TB10+BC10+KPV10)",
    code: "MULTI",
    category: "Blends",
    tagline: "Premium 4-peptide research blend: GHK-Cu 50 mg, TB-500 10 mg, BPC-157 10 mg, KPV 10 mg.",
    description:
      "The Gills Bio Lab Multi-Blend contains GHK-Cu (50 mg), TB-500 (10 mg), BPC-157 (10 mg), and KPV (10 mg) in a single precision vial. Supplied as a research chemical for laboratory use only. Suitable for in vitro studies examining multi-peptide interactions across regenerative, copper-binding, and anti-inflammatory research pathways.",
    quantity: "80 mg total / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 199,
    prices: [{ qty: "80 mg × 1", price: 199 }],
    inStock: true,
    featured: true,
    badge: "New",
  },
];

export const categories = [
  "All",
  "Peptides",
  "Growth Factors",
  "Neuropeptides",
  "GLP-1 / Metabolic",
  "Blends",
  "Hormonal Research",
  "Mitochondrial Research",
  "Metabolic / NAD",
  "Reconstitution Supplies",
];

export const featuredProducts = products.filter((p) => p.featured);

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
