export interface Product {
  id: string;
  name: string;
  code: string;
  category: string;
  tagline: string;
  description: string;
  quantity: string;
  form: string;
  purity: string;
  storage: string;
  handling: string;
  priceFrom: number;
  prices: { qty: string; price: number }[];
  inStock: boolean;
  featured: boolean;
  labFavorite?: boolean;
  badge?: string;
  slug: string;
}

export const products: Product[] = [
  {
    id: "bpc-157",
    slug: "bpc-157",
    name: "BPC-157",
    code: "BPC-157",
    category: "Peptides",
    tagline: "Body Protection Compound for advanced laboratory research applications.",
    description:
      "BPC-157 is a synthetic pentadecapeptide research chemical composed of 15 amino acids, supplied by Gills Bio Lab strictly for laboratory applications. This compound is not approved for human or veterinary use and must not be used for diagnosis, treatment, or any form of therapeutic or cosmetic application. Produced with a focus on consistency and reliability, BPC-157 is suitable for in vitro, analytical, and other controlled research settings where peptide behavior, stability, and interaction are under investigation.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 34.99,
    prices: [
      { qty: "5 mg × 1", price: 34.99 },
      { qty: "5 mg × 5", price: 149.99 },
      { qty: "5 mg × 10", price: 274.99 },
    ],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "tb-500",
    slug: "tb-500",
    name: "TB-500",
    code: "TB-500",
    category: "Peptides",
    tagline: "Thymosin Beta-4 fragment for in vitro peptide research studies.",
    description:
      "TB-500 is a synthetic analogue of the naturally occurring peptide Thymosin Beta-4. Supplied by Gills Bio Lab as a research chemical for laboratory use only. This compound is intended strictly for in vitro and analytical applications. Each unit is prepared and packaged to support demanding research workflows and storage conditions.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 39.99,
    prices: [
      { qty: "5 mg × 1", price: 39.99 },
      { qty: "5 mg × 5", price: 174.99 },
      { qty: "5 mg × 10", price: 319.99 },
    ],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "ghrp-6",
    slug: "ghrp-6",
    name: "GHRP-6",
    code: "GHRP-6",
    category: "Growth Factors",
    tagline: "Growth Hormone Releasing Peptide-6 research chemical for laboratory study.",
    description:
      "GHRP-6 is a synthetic hexapeptide research chemical supplied by Gills Bio Lab for laboratory applications only. It is not approved for human or veterinary use. Suitable for controlled research into growth hormone releasing peptides, receptor binding studies, and related in vitro investigations.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 24.99,
    prices: [
      { qty: "5 mg × 1", price: 24.99 },
      { qty: "5 mg × 5", price: 109.99 },
      { qty: "5 mg × 10", price: 199.99 },
    ],
    inStock: true,
    featured: false,
  },
  {
    id: "ghrp-2",
    slug: "ghrp-2",
    name: "GHRP-2",
    code: "GHRP-2",
    category: "Growth Factors",
    tagline: "Growth Hormone Releasing Peptide-2 for advanced in vitro research.",
    description:
      "GHRP-2 is a synthetic hexapeptide research chemical supplied by Gills Bio Lab for laboratory use only. This compound is suitable for in vitro and controlled research settings investigating growth hormone secretagogue activity and peptide interaction profiles.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 22.99,
    prices: [
      { qty: "5 mg × 1", price: 22.99 },
      { qty: "5 mg × 5", price: 99.99 },
      { qty: "5 mg × 10", price: 184.99 },
    ],
    inStock: true,
    featured: false,
  },
  {
    id: "cjc-1295",
    slug: "cjc-1295",
    name: "CJC-1295",
    code: "CJC-1295",
    category: "Growth Factors",
    tagline: "Long-acting GHRH analogue research chemical for laboratory peptide studies.",
    description:
      "CJC-1295 is a synthetic analogue of growth hormone releasing hormone supplied by Gills Bio Lab as a research chemical for laboratory use only. Each vial is prepared for demanding in vitro research workflows investigating GHRH receptor interactions and peptide stability.",
    quantity: "2 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 29.99,
    prices: [
      { qty: "2 mg × 1", price: 29.99 },
      { qty: "2 mg × 5", price: 129.99 },
      { qty: "2 mg × 10", price: 239.99 },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "ipamorelin",
    slug: "ipamorelin",
    name: "Ipamorelin",
    code: "IPM",
    category: "Growth Factors",
    tagline: "Selective growth hormone secretagogue for controlled research settings.",
    description:
      "Ipamorelin is a synthetic pentapeptide research chemical supplied by Gills Bio Lab for laboratory applications only. It is suitable for in vitro and analytical research investigating selective GH secretagogue receptor activity and peptide selectivity profiles.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 27.99,
    prices: [
      { qty: "5 mg × 1", price: 27.99 },
      { qty: "5 mg × 5", price: 119.99 },
      { qty: "5 mg × 10", price: 219.99 },
    ],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "mgf",
    slug: "mgf",
    name: "MGF",
    code: "MGF",
    category: "Growth Factors",
    tagline: "Mechano Growth Factor peptide research chemical for laboratory study.",
    description:
      "MGF (Mechano Growth Factor) is an isoform of IGF-1 supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research into growth factor peptides, receptor binding behavior, and related molecular investigations.",
    quantity: "2 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 32.99,
    prices: [
      { qty: "2 mg × 1", price: 32.99 },
      { qty: "2 mg × 5", price: 139.99 },
      { qty: "2 mg × 10", price: 254.99 },
    ],
    inStock: true,
    featured: false,
  },
  {
    id: "pt-141",
    slug: "pt-141",
    name: "PT-141",
    code: "PT-141",
    category: "Neuropeptides",
    tagline: "Melanocortin receptor agonist peptide for advanced laboratory research.",
    description:
      "PT-141 (Bremelanotide) is a synthetic cyclic heptapeptide research chemical supplied by Gills Bio Lab for laboratory use only. It is intended strictly for in vitro and controlled research investigating melanocortin receptor pharmacology and peptide behavior.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 44.99,
    prices: [
      { qty: "10 mg × 1", price: 44.99 },
      { qty: "10 mg × 5", price: 199.99 },
      { qty: "10 mg × 10", price: 374.99 },
    ],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "melanotan-2",
    slug: "melanotan-2",
    name: "Melanotan II",
    code: "MT-2",
    category: "Neuropeptides",
    tagline: "Melanocyte-stimulating hormone analogue research chemical.",
    description:
      "Melanotan II is a synthetic analogue of alpha-melanocyte-stimulating hormone supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro and controlled research into melanocortin receptor binding and peptide structural studies.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 42.99,
    prices: [
      { qty: "10 mg × 1", price: 42.99 },
      { qty: "10 mg × 5", price: 189.99 },
      { qty: "10 mg × 10", price: 349.99 },
    ],
    inStock: true,
    featured: false,
  },
  {
    id: "selank",
    slug: "selank",
    name: "Selank",
    code: "SEL",
    category: "Neuropeptides",
    tagline: "Anxiolytic heptapeptide research chemical for neuropeptide studies.",
    description:
      "Selank is a synthetic heptapeptide research chemical derived from tuftsin, supplied by Gills Bio Lab for laboratory use only. Suitable for in vitro and controlled neuropeptide research investigating GABAergic modulation and peptide–receptor interaction.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 36.99,
    prices: [
      { qty: "5 mg × 1", price: 36.99 },
      { qty: "5 mg × 5", price: 159.99 },
      { qty: "5 mg × 10", price: 294.99 },
    ],
    inStock: true,
    featured: false,
  },
  {
    id: "semax",
    slug: "semax",
    name: "Semax",
    code: "SMX",
    category: "Neuropeptides",
    tagline: "ACTH-derived neuropeptide research chemical for laboratory study.",
    description:
      "Semax is a synthetic heptapeptide research chemical derived from the ACTH sequence, supplied by Gills Bio Lab for laboratory use only. It is suitable for in vitro and controlled research into neuropeptide pharmacology and related peptide behavior studies.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 38.99,
    prices: [
      { qty: "5 mg × 1", price: 38.99 },
      { qty: "5 mg × 5", price: 169.99 },
      { qty: "5 mg × 10", price: 309.99 },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "epithalon",
    slug: "epithalon",
    name: "Epithalon",
    code: "EPT",
    category: "Peptides",
    tagline: "Telomeric tetrapeptide research chemical for laboratory applications.",
    description:
      "Epithalon is a synthetic tetrapeptide research chemical supplied by Gills Bio Lab for laboratory use only. Suitable for in vitro and analytical research investigating telomere-related peptide behavior, bioregulator studies, and related controlled applications.",
    quantity: "10 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 99%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 29.99,
    prices: [
      { qty: "10 mg × 1", price: 29.99 },
      { qty: "10 mg × 5", price: 129.99 },
      { qty: "10 mg × 10", price: 239.99 },
    ],
    inStock: true,
    featured: true,
    labFavorite: true,
  },
  {
    id: "dsip",
    slug: "dsip",
    name: "DSIP",
    code: "DSIP",
    category: "Neuropeptides",
    tagline: "Delta sleep-inducing peptide research chemical for laboratory use.",
    description:
      "DSIP (Delta Sleep-Inducing Peptide) is a nonapeptide research chemical supplied by Gills Bio Lab for laboratory use only. Suitable for in vitro and controlled neuropeptide research exploring peptide receptor pharmacology and sleep-related peptide behavior.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 97%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 31.99,
    prices: [
      { qty: "5 mg × 1", price: 31.99 },
      { qty: "5 mg × 5", price: 139.99 },
      { qty: "5 mg × 10", price: 254.99 },
    ],
    inStock: true,
    featured: false,
  },
  {
    id: "hexarelin",
    slug: "hexarelin",
    name: "Hexarelin",
    code: "HEX",
    category: "Growth Factors",
    tagline: "Hexapeptide growth hormone secretagogue for in vitro research.",
    description:
      "Hexarelin is a synthetic hexapeptide research chemical supplied by Gills Bio Lab for laboratory use only. It is a potent GH secretagogue suitable for in vitro research into receptor binding kinetics and growth factor peptide behavior.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 28.99,
    prices: [
      { qty: "5 mg × 1", price: 28.99 },
      { qty: "5 mg × 5", price: 124.99 },
      { qty: "5 mg × 10", price: 229.99 },
    ],
    inStock: false,
    featured: false,
    badge: "Backorder",
  },
  {
    id: "mod-grf",
    slug: "mod-grf",
    name: "Mod GRF (1-29)",
    code: "MOD-GRF",
    category: "Growth Factors",
    tagline: "Modified GHRH fragment research chemical for laboratory peptide studies.",
    description:
      "Mod GRF 1-29 is a shortened form of growth hormone releasing hormone supplied by Gills Bio Lab as a research chemical for laboratory use only. Suitable for in vitro research investigating truncated GHRH receptor interactions and related peptide stability studies.",
    quantity: "2 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 26.99,
    prices: [
      { qty: "2 mg × 1", price: 26.99 },
      { qty: "2 mg × 5", price: 114.99 },
      { qty: "2 mg × 10", price: 209.99 },
    ],
    inStock: true,
    featured: false,
  },
  {
    id: "kisspeptin-10",
    slug: "kisspeptin-10",
    name: "Kisspeptin-10",
    code: "KP-10",
    category: "Neuropeptides",
    tagline: "Hypothalamic neuropeptide research chemical for specialized laboratory applications.",
    description:
      "Kisspeptin-10 is a synthetic decapeptide research chemical supplied by Gills Bio Lab for laboratory use only. Suitable for in vitro and controlled research into GPR54 receptor pharmacology, reproductive neuroendocrinology, and related peptide investigations.",
    quantity: "5 mg / vial",
    form: "Lyophilized powder",
    purity: "≥ 98%",
    storage: "-20°C in a dry, dark location",
    handling: "Use appropriate personal protective equipment and follow institutional safety protocols.",
    priceFrom: 45.99,
    prices: [
      { qty: "5 mg × 1", price: 45.99 },
      { qty: "5 mg × 5", price: 204.99 },
      { qty: "5 mg × 10", price: 379.99 },
    ],
    inStock: true,
    featured: false,
  },
];

export const categories = ["All", "Peptides", "Growth Factors", "Neuropeptides"];

export const featuredProducts = products.filter((p) => p.featured);

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
